# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

parameters:
  displayName: ''
  workingDirectory: ''
  scheme: ''
  sdkurl: ''

jobs:
  - job: ${{ parameters.displayName }}Build
    displayName: ${{ parameters.displayName }}

    pool:
      vmImage: 'vs2017-win2016'

    variables:
      solution: '${{ parameters.workingDirectory }}/OpenLive.sln'
      buildPlatform: 'win32'
      buildConfiguration: 'Release'
   
    steps:

      - powershell: cicd/script/downloadsdk.ps1
   
      - task: ExtractFiles@1
        inputs:
          archiveFilePatterns: 'AgoraSDK.zip' 
          destinationFolder: 'AgoraSDK'
          
      - task: CopyFiles@2
        inputs:
          sourceFolder: 'AgoraSDK/Agora_Native_SDK_for_Windows_v2.9.3_FULL/sdk/'
          targetFolder: ${{ parameters.workingDirectory }}
              
      - task: VSBuild@1
        inputs:
          solution: '$(solution)'
          platform: '$(buildPlatform)'
          configuration: '$(buildConfiguration)'
          vsVersion: '15.0'
          msbuildArchitecture: 'x86'
   
      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: '${{ parameters.workingDirectory }}/Release/'
          includeRootFolder: true
          archiveType: 'zip'
          archiveFile: LiveStreaming.zip
          replaceExistingArchive: true
