/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_io_agora_ex_AudioVideoPreProcessing
#define _Included_io_agora_ex_AudioVideoPreProcessing
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_io_agora_ex_AudioVideoPreProcessing_doRegisterPreProcessing
  (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_io_agora_ex_AudioVideoPreProcessing_doDeregisterPreProcessing
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
